public class TestaContaComExcecaoChecked {

    /*Como o método deposita() é vazio, nenhuma exceção será criada. Mas, basta colocar o throws MinhaExcecao na assinatura e o compilador saberá
     que o método tem uma exceção do tipo Checked na sua assinatura. Por isso, temos que tomar uma atitude: ou colocamos throws MinhaExcecao na
     assinatura de main(), ou utilizamos try-catch.*/
    public static void main(String[] args){

        ContaFake  contaFake = new ContaFake();
        try {
            contaFake.deposita();
        }catch (MinhaExcecao minhaExcecao){
            System.out.println("Tratando excecao...");
        }
    }
}
